[package]
name = "edenfetch"
version = "0.1.0"
edition = "2021"
description = "edenfetch is a minimal fetch program written in Rust."

[dependencies]
nixinfo = "0.3.3"
colored = "2.0.0"
clap = {version = "3.0", features = ["derive"]}
